import java.io.IOException;

public class JavaFail155super {
    void doShir() throws  Exception {
        int i =11;
        String s = "" + i;
        s.length();
    }
}
